spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personaldb?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: marcelo
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update